spring:
  application:
    name: bank-service
  datasource:
    url: ${BANK_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/bankdb}
    username: ${BANK_SERVICE_DB_USERNAME:bank}
    password: ${BANK_SERVICE_DB_PASSWORD:bank}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${BANK_SERVICE_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework: INFO
