spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: bank-service
          uri: ${BANK_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/banks/**
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/products/**
        - id: offer-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/offers/**
      default-filters:
        - PreserveHostHeader

server:
  port: ${GATEWAY_SERVICE_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
